export default {
    readyToConnect: "Ready to connect...",
    connectUrlTitle: "WebSocket Server URL:",
    connectBtnText: "Connect",
    closeSocketBtnText: "Close Socket",
    sendBtnText: "Send",
    CPU: "CPU",
    RAM: "RAM",
    HDD: "HDD",
    ClosedStatus: "Closed",
    ClosingStatus: "Closing...",
    ConnectingStatus: "Connecting...",
    OpenStatus: "Open",
    UnknownState: "Unknown WebSocket State: ",
    ConnectionOpenedState: "Connection opened",
    SocketClosing: "Closing from client",
    Client: "Client",
    Server: "Server",
    CommonError: "Something went wrong.",
    Monitoring: "Monitoring",
    Resources: "Resources",
    CommunicationLog: "Communication Log",
    From: "From",
    To: "To",
    Message: "Message"
}